added VictoryPortal
FormidableLabs/victory-core pull request #141
Opened 2016-09-16 22:25 UTC by nfcampos

2016-09-17 19:07 UTC, boygirl requested changes
@nfcampos this all looks great. Approved pending my comment about refs.

2016-09-17 19:07 UTC, boygirl commented on src/victory-container/victory-container.js
> +        {React.cloneElement(this.props.portalComponent, {ref: "portal"})}
I think string refs are slated for deprecation. https://facebook.github.io/react/docs/more-about-refs.html#the-ref-string-attribute

Can you re-write this as a callback? Also, do you think there's a danger of naming collision with "portal"?

2016-09-18 15:39 UTC, nfcampos commented on src/victory-container/victory-container.js
> +        {React.cloneElement(this.props.portalComponent, {ref: "portal"})}
(i still end up always reaching for the string refs for some reason, will replace it)
naming collision with what?

2016-09-18 15:55 UTC, boygirl commented on src/victory-container/victory-container.js
> +        {React.cloneElement(this.props.portalComponent, {ref: "portal"})}
Never mind about the naming collision. My mistake.

2016-09-18 15:58 UTC, nfcampos commented on src/victory-container/victory-container.js
> +        {React.cloneElement(this.props.portalComponent, {ref: "portal"})}
The latest commit uses callback ref

2016-09-18 16:07 UTC, boygirl approved these changes

2016-09-18 16:07 UTC, boygirl commented
Awesome! I'll merge this now. Thanks you!

2016-09-18 16:07 UTC, merged