Update/prop types
FormidableLabs/victory-core pull request #236
Opened 2017-04-27 21:21 UTC by boygirl

cc/ @sto3psl  I think this PR fixes the last of the the compatibility issues for React 15.5

2017-04-27 21:50 UTC, ryan-roemer reviewed
Side note -- this is going to collide with my deps + eslint work that's refactoring various stuff, but I'll take the hit and clean up / merge resolve after you...

2017-04-27 21:50 UTC, ryan-roemer commented on demo/app.js
> +/*global window:false */
NIT: Suggest inline, comma separate with previous.

2017-04-27 21:50 UTC, ryan-roemer commented on test/client/spec/victory-util/prop-types.spec.js
> +      sandbox.spy(console, "warn");
GLOBAL -- We want `stub`s right? We don't want output all over our tests..

2017-04-27 21:50 UTC, sto3psl requested changes
This looks fine to me and can be merged if Travis passes. We can also put 

closes #232

into the description to automatically close my PR.

2017-04-27 21:50 UTC, sto3psl commented on src/victory-portal/portal.js
> +
This empty line is not really necessary.

2017-04-27 22:00 UTC, boygirl commented
@ryan-roemer should the `prop-types` package previously supplied by `react` be in `peerDependencies` or regular `dependencies`?

2017-04-27 22:15 UTC, boygirl commented
@sto3psl actually, I think this is going to be a major version change, as it will be a breaking change for users who aren't including `prop-types` in their projects. I'm going to delay putting this in for that reason.

2017-04-28 07:26 UTC, sto3psl commented
@boygirl Is it really? A lot of other libs (like [react-virtualized](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#971)) updated to `prop-types` with a patch release. It's also not really hard to "fix" it and everyone should transition to the new package. In production it's also not a problem since you should strip `PropTypes` there anyway.

2017-04-28 18:07 UTC, merged