Tests/scu
FormidableLabs/victory-core pull request #273
Opened 2017-07-24 23:17 UTC by boygirl

cc/ @ryan-roemer 
addresses comments in https://github.com/FormidableLabs/victory-core/pull/272

2017-07-24 23:35 UTC, ryan-roemer commented on test/client/spec/victory-util/collection.spec.js
> +    it("does not recursively check date objects", () => {
This doesn't seem to be the right test title. These dates _are_ being compared, and there isn't a nested object. As luck has it, they're all equal, but aren't necessarily.

We probably need to (1) retitle and/or refactor this test, and (2) make sure to use fake timers in our sandbox, amending the`sandbox.create()` call above to:

```js
      sandbox = sinon.sandbox.create({
        useFakeTimers: true
      });
```

2017-07-24 23:55 UTC, ryan-roemer commented on test/client/spec/victory-util/collection.spec.js
> +  });
Looking good generally, but I think we've got some corner cases to cover still. For example, we return `true` for `{}` vs. `[]` when that probably should be `false`. Here's a diff with that test and a whole bunch of lodash "isEqual" unit tests (_note_ we should not just copy them like in my diff, but use them as a starting point for our tests).

I think we'll want to look at this diff, and additional lodash isEqual unit tests for additional cases we should cover: https://github.com/lodash/lodash/blob/4.17.4/test/test.js#L9477

```diff
diff --git a/test/client/spec/victory-util/collection.spec.js b/test/client/spec/victory-util/collection.spec.js
index eeab6d4..4fa14d2 100644
--- a/test/client/spec/victory-util/collection.spec.js
+++ b/test/client/spec/victory-util/collection.spec.js
@@ -179,10 +179,12 @@ describe("collections", () => {
   });
 
 
-  describe("areVictoryPropsEqual", () => {
+  describe.only("areVictoryPropsEqual", () => {
     let sandbox;
     beforeEach(() => {
-      sandbox = sinon.sandbox.create();
+      sandbox = sinon.sandbox.create({
+        useFakeTimers: true
+      });
       sandbox.spy(Collection, "checkEquality");
     });
     afterEach(() => {
@@ -243,5 +245,39 @@ describe("collections", () => {
       expect(Collection.areVictoryPropsEqual(a, b)).to.equal(true);
     });
 
+    // FAILS
+    it("returns false for empty object vs. array", () => {
+      const a = { a: [] };
+      const b = { a: {} };
+      expect(Collection.areVictoryPropsEqual(a, b)).to.equal(false);
+      expect(Collection.checkEquality).calledOnce.and.returned(false);
+    });
+
+    // Disable symbol tests.
+    // https://github.com/lodash/lodash/blob/4.17.4/test/test.js#L9480-L9496
+    const symbol1 = true;
+    const symbol2 = false;
+    const pairs = [
+      [1, 1, true], [1, Object(1), true], [1, '1', false], [1, 2, false],
+      [-0, -0, true], [0, 0, true], [0, Object(0), true], [Object(0), Object(0), true], [-0, 0, true], [0, '0', false], [0, null, false],
+      [NaN, NaN, true], [NaN, Object(NaN), true], [Object(NaN), Object(NaN), true], [NaN, 'a', false], [NaN, Infinity, false],
+      ['a', 'a', true], ['a', Object('a'), true], [Object('a'), Object('a'), true], ['a', 'b', false], ['a', ['a'], false],
+      [true, true, true], [true, Object(true), true], [Object(true), Object(true), true], [true, 1, false], [true, 'a', false],
+      [false, false, true], [false, Object(false), true], [Object(false), Object(false), true], [false, 0, false], [false, '', false],
+      [symbol1, symbol1, true], [symbol1, Object(symbol1), true], [Object(symbol1), Object(symbol1), true], [symbol1, symbol2, false],
+      [null, null, true], [null, undefined, false], [null, {}, false], [null, '', false],
+      [undefined, undefined, true], [undefined, null, false], [undefined, '', false]
+    ];
+
+    // SOME FAIL
+    pairs.forEach((vals) => {
+      it(`lodash primitive comparison: ${vals}`, () => {
+        const a = vals[0];
+        const b = vals[1];
+        const expected = vals[2];
+        expect(Collection.areVictoryPropsEqual(a, b)).to.equal(expected);
+      });
+    });
+
   });
 });
```

2017-07-24 23:56 UTC, ryan-roemer requested changes
Thanks for getting this started so quickly!

Code changes look good. Tests cases I think could use more coverage, and I think we can use lodash's for inspiration!

2017-07-25 05:12 UTC, boygirl commented on test/client/spec/victory-util/collection.spec.js
> +    it("does not recursively check date objects", () => {
You're right, these should be exact dates instead. I included this test to distinguish date objects from plain objects, as plain objects should be recursively checked, and dates should not.

2017-07-25 17:52 UTC, boygirl commented
This equality checker differs from lodash `isEqual` in the following ways:
- Functions are marked as equal (By design-- this was the main impetus for writing a new function)
- Does not handle symbols or maps
- Returns false when checking the equality of things like `1` vs. `Object(1)` whereas isEqual returns true
- Does not handle circular references in objects and arrays

2017-07-25 17:56 UTC, ryan-roemer commented on test/client/spec/victory-util/collection.spec.js
> +    const pairs = [
We need to either (1) attribute the lodash license and make sure it's compatible with Victory's for this literal copy and paste, OR (2) use it for inspiration / cases but not copy and paste it. Either way is fine.

2017-07-25 17:57 UTC, ryan-roemer commented on test/client/spec/victory-util/collection.spec.js
> +  });
These were only the "primitives" tests for lodashs isEqual. There are many others we should incorporate as well if they apply to scenarios we need to support.

2017-07-25 18:27 UTC, ryan-roemer commented on src/victory-util/collection.js
> +    return undefined;
We should document this internal function to say that it's tri-state and spell out that you cannot just use it straight up without comparing the type of the return value.

2017-07-25 18:36 UTC, boygirl commented on src/victory-util/collection.js
> +    return undefined;
better to also make it an actual internal function?

2017-07-25 18:37 UTC, ryan-roemer commented on src/victory-util/collection.js
> +    return undefined;
Might be nice -- could add a few specific tests if warranted too.

2017-07-25 19:03 UTC, boygirl commented
@ryan-roemer this is feeling complete enough to me. Good to merge?

2017-07-26 23:13 UTC, ryan-roemer commented
@boygirl -- Did you see my question about https://github.com/FormidableLabs/victory-core/pull/273#discussion_r129379054 ?

Given that the lodash primitives examples yielded some good bugs should we look at their _other_ cases too? (Not just the ones I pasted for you, actually looking at their other isEqual tests like:

- https://github.com/lodash/lodash/blob/4.17.4/test/test.js#L9509
- https://github.com/lodash/lodash/blob/4.17.4/test/test.js#L9587
- https://github.com/lodash/lodash/blob/4.17.4/test/test.js#L9625
- https://github.com/lodash/lodash/blob/4.17.4/test/test.js#L9833

... and everything else that they're already done the work for...)

2017-07-27 00:19 UTC, boygirl commented
Yep, [this commit](https://github.com/FormidableLabs/victory-core/pull/273/commits/abe53957c6cbad7a3303daab06907cc47956e4eb) added specs for equality checking for arrays, plain objects, nested arrays, nested objects, and mixed collections. I feel like those are the relevant checks given that this method will only ever be used for checking equality on validated props objects and a state object.

2017-07-27 01:06 UTC, ryan-roemer approved these changes

2017-07-27 01:06 UTC, ryan-roemer commented
OK!

2017-07-27 01:46 UTC, merged